a = int(input("Enter the First number: "))
b = int(input("Enter the Second number: "))
c = int(input("Enter the Third number: "))
print("\nLogical Operations Results:")
print((a > b) and (b > c))
print((a > b) or (b > c))
print(not(a > b))
print(not(b > c))
